name: Snake

on:
  push:
    branches: [ main ]

  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: dist
          fqdn: ${{ secrets.DOMAIN }}
          cname: ${{ secrets.CNAME }}
          publish_dir: .
          enable_upload: true
          commit_message: Update snake animation ({{ env.GITHUB_RUN_NUMBER }})
